export const CANDIDATE_PROFILE_SET_DATA = "CANDIDATE_PROFILE_SET_DATA";

export const CANDIDATE_CURRENT_STATUS = "CANDIDATE_CURRENT_STATUS";

export const SET_CANDIDATE__APPLIED_JOBS = "SET_CANDIDATE__APPLIED_JOBS";

export const SET_CANDIDATE_EXPERIENCE_TYPE = "SET_CANDIDATE_EXPERIENCE_TYPE";

export const SET_CANDIDATE_DEGREE_TITLES = "SET_CANDIDATE_DEGREE_TITLES";

export const SET_CANDIDATE_INSTITUTION_TYPE = "SET_CANDIDATE_INSTITUTION_TYPE";

export const SET_CANDIDATE_ALL_ANSWERS = "SET_CANDIDATE_ALL_ANSWERS";

export const SET_CANDIDATE_JOB_VIEW_DATA = "SET_CANDIDATE_JOB_VIEW_DATA";

export const SET_CANDIDATE_JOBS = "SET_CANDIDATE_JOBS";

export const SET_CANDIDATE_CERTIFICATE_TITLES = "SET_CANDIDATE_CERTIFICATE_TITLES";

export const SET_ALL_INDUSTRIES = "SET_ALL_INDUSTRIES";

export const SET_ALL_FUNCTIONS = "SET_ALL_FUNCTIONS";

export const SET_JOB_DESCRIPTION = "SET_JOB_DESCRIPTION";

export const SET_ALL_MAJOR_MINOR = "SET_ALL_MAJOR_MINOR";

export const SET_DATA_FLAG = "SET_DATA_FLAG";

export const SET_CURRENT_GOALS = "SET_CURRENT_GOALS";

export const SET_CANDIDATE_HEALTH_CARE_GOALS = "SET_CANDIDATE_HEALTH_CARE_GOALS";

export const SET_CANDIDATE_ALTERNATIVE_GOALS = "SET_CANDIDATE_ALTERNATIVE_GOALS";

export const SET_CANDIDATE_GOALS_BY_ID = "SET_CANDIDATE_GOALS_BY_ID";



